export default {
  FETCH_INITIAL_DATA: 'FETCH_INITIAL_DATA',
  SET_PATH: 'SET_PATH',
  MEN: 'MEN',
  WOMEN: 'WOMEN',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  CHECK_OUT: 'CHECK_OUT'
}
